---
- name: Set and print a variable
  hosts: localhost
  gather_facts: no  # Disable gathering facts to speed up the playbook

  vars:
    my_variable: "Hello, Ansible!"

  tasks:
    - name: Print the variable value
      debug:
        var: my_variable

